// 24 UR ODBOJKE — podatki javne strani (index.html na GitHub Pages).
// Rezultat vpiši kot [točke levo, točke desno]; null = tekma še ni igrana.
// Objava: git add data.js && git commit -m "rezultati" && git push  (stran je sveža v ~1 min)
// Nov token (po spremembi razporeda) naredi gumb "Kopiraj za objavo" v uredi.html.
PUB = {
updated: "2026-07-15T20:45:12.047Z",
token: // zakodiran razpored — ne urejaj ročno
"WzEseyJnaXJscyI6WyJORcW9QSBCRVJDRSIsIk5JTkEgVE9NQcW9SU4iLCJFUklLQSBNT0hPUknEjCIsIk1BUlXFoEEgRE9MSU5BUiIsIkxJWkEgUE9MSkFOxaBFSyIsIkxJQSBCRVJDRSIsIkxPVEkgR1JVxaBLT1ZOSkFLIiwiTUHFoEEgVkVHRUxKIiwiVElBIE1PxIxOSUsiLCJMRU5BIEtSSVNUQU4iLCJFTUEgS0FWxIxJxIwiXSwiYm95cyI6WyJKQUtBIEtPUEHEjCIsIlJPSyBNUk9VTEUiLCJNQVRJQyBFTklLTyIsIkpBTiBHT1ZFS0FSIiwiSlXFoCBCVVJKRUsiLCJET01FTiBET0xFTkMiLCJLUknFoFRPRiBHQU5UQVIiLCJEQVZJRCDFoEVOSyIsIkpBTiBET0xFTkMiLCJVUkJBTiBKRVJFQiIsIkxVWUdHWSIsIkJSSUMgS1JPTE5JSyJdLCJzdGFydENsb2NrIjoiMTc6MDAiLCJzdGFydERhdGUiOiIyMDI2LTA3LTE3IiwibWF0Y2hNaW4iOjM1LCJnYXBNaW4iOjUsIm5pZ2h0U3RhcnRDbG9jayI6IjAwOjAwIiwibmlnaHRFbmRDbG9jayI6IjA0OjAwIiwicGF1c2VPbiI6dHJ1ZSwicGF1c2VDbG9jayI6IjAxOjAwIiwicGF1c2VNaW4iOjEyMCwic2VlZCI6NjE1MTI0fSxbWzAsNyw4LDEsOSwyLDAsLTEsLTEsMF0sWzEsMywwLDgsMSw5LDAsLTEsLTEsMF0sWzIsMCw1LDUsNiw2LDAsLTEsLTEsMF0sWzMsMCw0LDQsNyw3LDAsLTEsLTEsMF0sWzQsMCwyLDIsOSw5LDAsLTEsLTEsMF0sWzUsMCwxLDExLDAsMCwwLC0xLC0xLDBdLFs2LDEsNyw2LDgsNywwLC0xLC0xLDBdLFs3LDEwLDEwLDExLDksMTAsMCwtMSwtMSwwXSxbOCw0LDEsOCw0LDAsMCwtMSwtMSwwXSxbOSw1LDMsOSw2LDEsMCwtMSwtMSwwXSxbMTAsMyw3LDQsNSwyLDAsLTEsLTEsMF0sWzExLDYsMiwxMSwxLDYsMCwtMSwtMSwwXSxbMTIsMiw5LDcsMTAsOCwwLC0xLC0xLDBdLFsxMyw1LDQsMTAsNSwwLDAsLTEsLTEsMF0sWzE0LDAsMywzLDgsOCwwLC0xLC0xLDBdLFsxNSw1LDAsNiw5LDQsMCwtMSwtMSwwXSxbMTYsNyw1LDksMSw1LDAsLTEsLTEsMF0sWzE3LDMsMTAsNywyLDEwLDAsLTEsLTEsMF0sWzE4LDMsNywxMSw2LDMsMCwtMSwtMSwwXSxbMTksMyw4LDUsNCwxLDAsLTEsLTEsMF0sWzIwLDQsMiw5LDMsMTAsMCwtMSwtMSwwXSxbMjEsOSw5LDAsNSw3LDAsLTEsLTEsMF0sWzIyLDQsMTAsNiw2LDIsMCwtMSwtMSwwXSxbMjMsOSwxLDMsMiw0LDAsLTEsLTEsMF0sWzI0LDEwLDAsMSw3LDgsMCwtMSwtMSwwXSxbMjUsNiw1LDEwLDgsMiwwLC0xLC0xLDBdLFsyNiwzLDksNiwzLDAsMCwtMSwtMSwwXSxbMjcsNSwwLDExLDEwLDUsMCwtMSwtMSwwXSxbMjgsOCw2LDksNCw3LDAsLTEsLTEsMF0sWzI5LDIsNSwzLDMsMSwwLC0xLC0xLDBdLFszMCw1LDIsOCw3LDIsMCwtMSwtMSwwXSxbMzEsNyw2LDEwLDAsNCwwLC0xLC0xLDBdLFszMiwxMCwxMCwwLDgsOSwwLC0xLC0xLDBdLFszMyw0LDksNSw3LDMsMCwtMSwtMSwwXSxbMzQsNyw0LDExLDMsNywwLC0xLC0xLDBdLFszNSw5LDgsMTAsNiw4LDAsLTEsLTEsMF0sWzM2LDEsNSw0LDEwLDksMCwtMSwtMSwwXSxbMzcsMSwzLDIsMSwwLDAsLTEsLTEsMF0sWzM4LDYsMiw3LDAsNSwwLC0xLC0xLDBdLFszOSw5LDEwLDEsNCw2LDAsLTEsLTEsMF0sWzQwLDQsOSwxMSw4LDQsMCwtMSwtMSwwXSxbNDEsMiw3LDUsMSwxMCwwLC0xLC0xLDBdLFs0MiwyLDYsNCwyLDAsMCwtMSwtMSwwXSxbNDMsNCwwLDcsNSwxLDAsLTEsLTEsMF0sWzQ0LDgsNywxMCwzLDYsMCwtMSwtMSwwXSxbNDUsNiw0LDksOSwzLDAsLTEsLTEsMF0sWzQ2LDgsNiwxMSw1LDgsMCwtMSwtMSwwXSxbNDcsOCw4LDAsMiw1LDAsLTEsLTEsMF0sWzQ4LDgsOSwxLDEsNCwwLC0xLC0xLDBdLFs0OSw4LDEwLDIsMCwzLDAsLTEsLTEsMF0sWzUwLDksOCwxMSw3LDksMCwtMSwtMSwwXSxbNTEsNyw0LDgsMiw2LDAsLTEsLTEsMF0sWzUyLDksMCwyLDMsNSwwLC0xLC0xLDBdLFs1MywwLDEsMSwxMCwxMCwwLC0xLC0xLDBdLFs1NCwxMCwyLDMsNSw2LDAsLTEsLTEsMF0sWzU1LDEwLDMsNCw0LDUsMCwtMSwtMSwwXSxbNTYsMTAsMSwyLDYsNywwLC0xLC0xLDBdLFs1NywyLDgsNiwwLDksMCwtMSwtMSwwXSxbNTgsNyw3LDAsMTAsMywwLC0xLC0xLDBdLFs1OSwxLDMsMTEsMiwxLDAsLTEsLTEsMF0sWzYwLDEsNiw1LDksOCwwLC0xLC0xLDBdLFs2MSwxLDQsMywwLDEwLDAsLTEsLTEsMF0sWzYyLDYsMyw4LDEwLDQsMCwtMSwtMSwwXSxbNjMsNiw2LDAsNywxLDAsLTEsLTEsMF0sWzY0LDUsMSw3LDgsMywwLC0xLC0xLDBdLFs2NSwyLDUsMTEsNCwyLDAsLTEsLTEsMF1dLFtbImI1MDAxIiwibTAiLCJtMiIsIm00IiwibTYiLCJtNyIsIm05IiwibTExIiwibTEzIiwibTE0IiwibTE2IiwiYjQwMDAiLCJtMTkiLCJtMjEiLCJtMjMiLCJtMjUiLCJtMjciLCJtMjkiLCJtMzEiLCJtMzMiLCJtMzUiLCJtMzciLCJtMzkiLCJtNDEiLCJtNDIiLCJtNDQiLCJtNDYiLCJtNDgiLCJtNTAiLCJtNTIiLCJiNDAwMSIsIm01NSIsIm01NyIsIm01OSIsIm02MSIsIm02MiIsIm02NCJdLFsiYjUwMDIiLCJtMSIsIm0zIiwibTUiLCJiNDAwMiIsIm04IiwibTEwIiwibTEyIiwiYjQwMDMiLCJtMTUiLCJtMTciLCJtMTgiLCJtMjAiLCJtMjIiLCJtMjQiLCJtMjYiLCJtMjgiLCJtMzAiLCJtMzIiLCJtMzQiLCJtMzYiLCJtMzgiLCJtNDAiLCJiNDAwNCIsIm00MyIsIm00NSIsIm00NyIsIm00OSIsIm01MSIsIm01MyIsIm01NCIsIm01NiIsIm01OCIsIm02MCIsImI0MDA1IiwibTYzIiwibTY1Il1dLFtbNDAwMCw0MCwiUHJvc3RvIGlncmnFocSNZSJdLFs0MDAxLDQwLCJQcm9zdG8gaWdyacWhxI1lIl0sWzQwMDIsNDAsIlByb3N0byBpZ3JpxaHEjWUiXSxbNDAwMyw0MCwiUHJvc3RvIGlncmnFocSNZSJdLFs0MDA0LDQwLCJQcm9zdG8gaWdyacWhxI1lIl0sWzQwMDUsNDAsIlByb3N0byBpZ3JpxaHEjWUiXSxbNTAwMSwzMCwiUHJlbW9yIl0sWzUwMDIsMzAsIlByZW1vciJdXV0",
rezultati: {
 0: null,  // 17:30 · 1 · TIA MOČNIK & ROK MROULE — LENA KRISTAN & MATIC ENIKO
 2: null,  // 18:10 · 1 · LIA BERCE & DOMEN DOLENC — LOTI GRUŠKOVNJAK & KRIŠTOF GANTAR
 4: null,  // 18:50 · 1 · ERIKA MOHORIČ & MATIC ENIKO — LENA KRISTAN & URBAN JEREB
 6: null,  // 19:30 · 1 · MAŠA VEGELJ & KRIŠTOF GANTAR — TIA MOČNIK & DAVID ŠENK
 7: null,  // 20:10 · 1 · EMA KAVČIČ & BRIC KROLNIK — LENA KRISTAN & LUYGGY
 9: null,  // 20:50 · 1 · MARUŠA DOLINAR & URBAN JEREB — LOTI GRUŠKOVNJAK & ROK MROULE
 11: null,  // 21:30 · 1 · ERIKA MOHORIČ & BRIC KROLNIK — NINA TOMAŽIN & KRIŠTOF GANTAR
 13: null,  // 22:10 · 1 · LIZA POLJANŠEK & LUYGGY — LIA BERCE & JAKA KOPAČ
 14: null,  // 22:50 · 1 · MARUŠA DOLINAR & JAN GOVEKAR — TIA MOČNIK & JAN DOLENC
 16: null,  // 23:30 · 1 · LIA BERCE & URBAN JEREB — NINA TOMAŽIN & DOMEN DOLENC
 19: null,  // 00:50 · 1 · TIA MOČNIK & DOMEN DOLENC — LIZA POLJANŠEK & ROK MROULE
 21: null,  // 01:30 · 1 · LENA KRISTAN & JAKA KOPAČ — LIA BERCE & DAVID ŠENK
 23: null,  // 02:10 · 1 · NINA TOMAŽIN & JAN GOVEKAR — ERIKA MOHORIČ & JUŠ BURJEK
 25: null,  // 02:50 · 1 · LIA BERCE & LUYGGY — TIA MOČNIK & MATIC ENIKO
 27: null,  // 03:30 · 1 · NEŽA BERCE & BRIC KROLNIK — EMA KAVČIČ & DOMEN DOLENC
 29: null,  // 04:10 · 1 · LIA BERCE & JAN GOVEKAR — MARUŠA DOLINAR & ROK MROULE
 31: null,  // 04:50 · 1 · LOTI GRUŠKOVNJAK & LUYGGY — NEŽA BERCE & JUŠ BURJEK
 33: null,  // 05:30 · 1 · LENA KRISTAN & DOMEN DOLENC — MAŠA VEGELJ & JAN GOVEKAR
 35: null,  // 06:10 · 1 · TIA MOČNIK & LUYGGY — LOTI GRUŠKOVNJAK & JAN DOLENC
 37: null,  // 06:50 · 1 · MARUŠA DOLINAR & MATIC ENIKO — NINA TOMAŽIN & JAKA KOPAČ
 39: null,  // 07:30 · 1 · EMA KAVČIČ & ROK MROULE — LIZA POLJANŠEK & KRIŠTOF GANTAR
 41: null,  // 08:10 · 1 · MAŠA VEGELJ & DOMEN DOLENC — NINA TOMAŽIN & LUYGGY
 42: null,  // 08:50 · 1 · LOTI GRUŠKOVNJAK & JUŠ BURJEK — ERIKA MOHORIČ & JAKA KOPAČ
 44: null,  // 09:30 · 1 · MAŠA VEGELJ & LUYGGY — MARUŠA DOLINAR & KRIŠTOF GANTAR
 46: null,  // 10:10 · 1 · LOTI GRUŠKOVNJAK & BRIC KROLNIK — LIA BERCE & JAN DOLENC
 48: null,  // 10:50 · 1 · LENA KRISTAN & ROK MROULE — NINA TOMAŽIN & JUŠ BURJEK
 50: null,  // 11:30 · 1 · TIA MOČNIK & BRIC KROLNIK — MAŠA VEGELJ & URBAN JEREB
 52: null,  // 12:10 · 1 · NEŽA BERCE & MATIC ENIKO — MARUŠA DOLINAR & DOMEN DOLENC
 55: null,  // 13:30 · 1 · MARUŠA DOLINAR & JUŠ BURJEK — LIZA POLJANŠEK & DOMEN DOLENC
 57: null,  // 14:10 · 1 · TIA MOČNIK & KRIŠTOF GANTAR — NEŽA BERCE & URBAN JEREB
 59: null,  // 14:50 · 1 · MARUŠA DOLINAR & BRIC KROLNIK — ERIKA MOHORIČ & ROK MROULE
 61: null,  // 15:30 · 1 · LIZA POLJANŠEK & JAN GOVEKAR — NEŽA BERCE & LUYGGY
 62: null,  // 16:10 · 1 · MARUŠA DOLINAR & JAN DOLENC — EMA KAVČIČ & JUŠ BURJEK
 64: null,  // 16:50 · 1 · NINA TOMAŽIN & DAVID ŠENK — TIA MOČNIK & JAN GOVEKAR
 1: null,  // 17:30 · 2 · NEŽA BERCE & JAN DOLENC — NINA TOMAŽIN & URBAN JEREB
 3: null,  // 18:10 · 2 · LIZA POLJANŠEK & JUŠ BURJEK — MAŠA VEGELJ & DAVID ŠENK
 5: null,  // 18:50 · 2 · NINA TOMAŽIN & BRIC KROLNIK — NEŽA BERCE & JAKA KOPAČ
 8: null,  // 20:10 · 2 · NINA TOMAŽIN & JAN DOLENC — LIZA POLJANŠEK & JAKA KOPAČ
 10: null,  // 20:50 · 2 · MAŠA VEGELJ & JUŠ BURJEK — LIA BERCE & MATIC ENIKO
 12: null,  // 21:30 · 2 · LENA KRISTAN & DAVID ŠENK — EMA KAVČIČ & JAN DOLENC
 15: null,  // 22:50 · 2 · NEŽA BERCE & KRIŠTOF GANTAR — LENA KRISTAN & JUŠ BURJEK
 17: null,  // 23:30 · 2 · EMA KAVČIČ & DAVID ŠENK — ERIKA MOHORIČ & LUYGGY
 18: null,  // 00:10 · 2 · MAŠA VEGELJ & BRIC KROLNIK — LOTI GRUŠKOVNJAK & JAN GOVEKAR
 20: null,  // 00:50 · 2 · ERIKA MOHORIČ & URBAN JEREB — MARUŠA DOLINAR & LUYGGY
 22: null,  // 01:30 · 2 · EMA KAVČIČ & KRIŠTOF GANTAR — LOTI GRUŠKOVNJAK & MATIC ENIKO
 24: null,  // 02:10 · 2 · NEŽA BERCE & ROK MROULE — MAŠA VEGELJ & JAN DOLENC
 26: null,  // 02:50 · 2 · LENA KRISTAN & KRIŠTOF GANTAR — MARUŠA DOLINAR & JAKA KOPAČ
 28: null,  // 03:30 · 2 · LOTI GRUŠKOVNJAK & URBAN JEREB — LIZA POLJANŠEK & DAVID ŠENK
 30: null,  // 04:10 · 2 · ERIKA MOHORIČ & JAN DOLENC — MAŠA VEGELJ & MATIC ENIKO
 32: null,  // 04:50 · 2 · EMA KAVČIČ & JAKA KOPAČ — TIA MOČNIK & URBAN JEREB
 34: null,  // 05:30 · 2 · LIZA POLJANŠEK & BRIC KROLNIK — MARUŠA DOLINAR & DAVID ŠENK
 36: null,  // 06:10 · 2 · LIA BERCE & JUŠ BURJEK — EMA KAVČIČ & URBAN JEREB
 38: null,  // 06:50 · 2 · ERIKA MOHORIČ & DAVID ŠENK — NEŽA BERCE & DOMEN DOLENC
 40: null,  // 07:30 · 2 · LENA KRISTAN & BRIC KROLNIK — TIA MOČNIK & JUŠ BURJEK
 43: null,  // 08:50 · 2 · NEŽA BERCE & DAVID ŠENK — LIA BERCE & ROK MROULE
 45: null,  // 09:30 · 2 · LIZA POLJANŠEK & URBAN JEREB — LENA KRISTAN & JAN GOVEKAR
 47: null,  // 10:10 · 2 · TIA MOČNIK & JAKA KOPAČ — ERIKA MOHORIČ & DOMEN DOLENC
 49: null,  // 10:50 · 2 · EMA KAVČIČ & MATIC ENIKO — NEŽA BERCE & JAN GOVEKAR
 51: null,  // 11:30 · 2 · LIZA POLJANŠEK & JAN DOLENC — ERIKA MOHORIČ & KRIŠTOF GANTAR
 53: null,  // 12:10 · 2 · NINA TOMAŽIN & ROK MROULE — EMA KAVČIČ & LUYGGY
 54: null,  // 12:50 · 2 · ERIKA MOHORIČ & JAN GOVEKAR — LIA BERCE & KRIŠTOF GANTAR
 56: null,  // 13:30 · 2 · NINA TOMAŽIN & MATIC ENIKO — LOTI GRUŠKOVNJAK & DAVID ŠENK
 58: null,  // 14:10 · 2 · MAŠA VEGELJ & JAKA KOPAČ — EMA KAVČIČ & JAN GOVEKAR
 60: null,  // 14:50 · 2 · LOTI GRUŠKOVNJAK & DOMEN DOLENC — LENA KRISTAN & JAN DOLENC
 63: null,  // 16:10 · 2 · LOTI GRUŠKOVNJAK & JAKA KOPAČ — MAŠA VEGELJ & ROK MROULE
 65: null,  // 16:50 · 2 · LIA BERCE & BRIC KROLNIK — LIZA POLJANŠEK & MATIC ENIKO
}
};
