// 24 UR ODBOJKE — podatki javne strani (index.html na GitHub Pages).
// Rezultat vpiši kot [točke levo, točke desno]; null = tekma še ni igrana.
// Objava: git add data.js && git commit -m "rezultati" && git push  (stran je sveža v ~1 min)
// Nov token (po spremembi razporeda) naredi gumb "Kopiraj za objavo" v uredi.html.
// !!! SIMULIRANI PODATKI za preizkus — pravi turnir jih bo zamenjal. !!!
PUB = {
updated: "2026-07-09T20:08:54.327Z",
token: // zakodiran razpored — ne urejaj ročno
"WzEseyJnaXJscyI6WyJORcW9QSBCRVJDRSIsIk5JTkEgVE9NQcW9SU4iLCJFUklLQSBNT0hPUknEjCIsIk1BUlXFoEEgRE9MSU5BUiIsIkxJWkEgUE9MSkFOxIzFoEVLIiwiTElBIEJFUkNFIiwiTE9USSBHUlXFoEtPIFZBTkpBSyIsIk1BxaBBIFZFR0VMSiIsIlBVTkNBIDkiLCJQVU5DQSAxMCIsIlBVTkNBIDExIiwiUFVOQ0EgMTIiXSwiYm95cyI6WyJKQUtBIEtPUEHEjCIsIlJPSyBNUk9VTEUiLCJNQVRJQyBFTklLTyIsIkpBTiBHT1ZFS0FSIiwiSlXFoCBCVVJKRUsiLCJET01FTiBET0xFTkMiLCJLUknFoFRPRiBHQU5UQVIiLCJEQVZJRCDFoEVOSyIsIkpBTiBET0xFTkMiLCJVUkJBTiBKRVJFQiIsIkxVWUdHWSIsIkpBS0EgRU5JS08iXSwic3RhcnRDbG9jayI6IjE3OjAwIiwic3RhcnREYXRlIjoiMjAyNi0wNy0wOSIsIm1hdGNoTWluIjoyMCwiZ2FwTWluIjoxMCwibmlnaHRTdGFydENsb2NrIjoiMDA6MDAiLCJuaWdodEVuZENsb2NrIjoiMDQ6MDAiLCJwYXVzZU9uIjp0cnVlLCJwYXVzZUNsb2NrIjoiMDE6MDAiLCJwYXVzZU1pbiI6MTIwLCJzZWVkIjo0MjQyNDJ9LFtbMCwwLDAsMCw2LDYsMCwtMSwtMV0sWzEsMCwxLDEsNCw0LDAsLTEsLTFdLFsyLDAsMiwyLDUsNSwwLC0xLC0xXSxbMywwLDMsMyw3LDcsMCwtMSwtMV0sWzQsMCw4LDgsMTEsMTEsMCwtMSwtMV0sWzUsMCw5LDksMTAsMTAsMCwtMSwtMV0sWzYsMSwwLDEsOCw5LDAsLTEsLTFdLFs3LDEsMSwyLDExLDAsMCwtMSwtMV0sWzgsMSwyLDMsMTAsMTEsMCwtMSwtMV0sWzksMSwzLDQsNCw1LDAsLTEsLTFdLFsxMCwxLDUsNiw5LDEwLDAsLTEsLTFdLFsxMSwxLDYsNyw3LDgsMCwtMSwtMV0sWzEyLDIsMCwyLDksMTEsMCwxMCwxMF0sWzEzLDIsMSwzLDMsNSwwLC0xLC0xXSxbMTQsMiwyLDQsNyw5LDAsMjUsMjFdLFsxNSwyLDQsNiw1LDcsMCwxOCwxNl0sWzE2LDIsNiw4LDgsMTAsMCwtMSwtMV0sWzE3LDIsMTAsMCwxMSwxLDAsMTcsMTNdLFsxOCwzLDAsMywxLDQsMCwxOCwyMV0sWzE5LDMsMiw1LDQsNywwLC0xLC0xXSxbMjAsMywzLDYsNiw5LDAsLTEsLTFdLFsyMSwzLDUsOCwxMCwxLDAsLTEsLTFdLFsyMiwzLDcsMTAsMTEsMiwwLC0xLC0xXSxbMjMsMyw4LDExLDksMCwwLC0xLC0xXSxbMjQsNCwwLDQsMTAsMiwwLDE0LDEyXSxbMjUsNCwxLDUsNiwxMCwwLC0xLC0xXSxbMjYsNCwyLDYsMTEsMywwLDIyLDE4XSxbMjcsNCwzLDcsOSwxLDAsLTEsLTFdLFsyOCw0LDQsOCw4LDAsMCwxMywxNV0sWzI5LDQsNSw5LDcsMTEsMCwtMSwtMV0sWzMwLDUsMCw1LDMsOCwwLC0xLC0xXSxbMzEsNSwxLDYsOCwxLDAsMTQsMThdLFszMiw1LDIsNyw2LDExLDAsLTEsLTFdLFszMyw1LDQsOSw5LDIsMCwtMSwtMV0sWzM0LDUsNSwxMCwxMSw0LDAsLTEsLTFdLFszNSw1LDcsMCwxMCwzLDAsLTEsLTFdLFszNiw2LDAsNiwxMSw1LDAsLTEsLTFdLFszNyw2LDEsNywxMCw0LDAsLTEsLTFdLFszOCw2LDIsOCw5LDMsMCwtMSwtMV0sWzM5LDYsMyw5LDUsMTEsMCwtMSwtMV0sWzQwLDYsNCwxMCw2LDAsMCwtMSwtMV0sWzQxLDYsNywxLDgsMiwwLC0xLC0xXSxbNDIsNywwLDcsNSwwLDAsLTEsLTFdLFs0Myw3LDEsOCwyLDksMCwtMSwtMV0sWzQ0LDcsMywxMCw4LDMsMCwxNCwyNV0sWzQ1LDcsNCwxMSw3LDIsMCwtMSwtMV0sWzQ2LDcsNiwxLDEwLDUsMCwxMywyNF0sWzQ3LDcsOSw0LDExLDYsMCwtMSwtMV0sWzQ4LDgsMCw4LDQsMCwwLC0xLC0xXSxbNDksOCwxLDksOSw1LDAsLTEsLTFdLFs1MCw4LDIsMTAsOCw0LDAsMTMsMTJdLFs1MSw4LDMsMTEsMTAsNiwwLC0xLC0xXSxbNTIsOCw1LDEsNywzLDAsLTEsLTFdLFs1Myw4LDYsMiwxMSw3LDAsLTEsLTFdLFs1NCw5LDAsOSw2LDMsMCwtMSwtMV0sWzU1LDksMSwxMCwxMCw3LDAsLTEsLTFdLFs1Niw5LDIsMTEsMywwLDAsLTEsLTFdLFs1Nyw5LDQsMSwxMSw4LDAsLTEsLTFdLFs1OCw5LDUsMiw4LDUsMCwtMSwtMV0sWzU5LDksNyw0LDksNiwwLC0xLC0xXSxbNjAsMTAsMCwxMCwzLDEsMCwtMSwtMV0sWzYxLDEwLDEsMTEsNyw1LDAsMTIsMTRdLFs2MiwxMCwyLDAsNiw0LDAsLTEsLTFdLFs2MywxMCw0LDIsNSwzLDAsMTgsMjJdLFs2NCwxMCw4LDYsMTAsOCwwLC0xLC0xXSxbNjUsMTAsOSw3LDExLDksMCwtMSwtMV0sWzY2LDExLDAsMTEsMTEsMTAsMCwxMSwyNF0sWzY3LDExLDEsMCw4LDcsMCwtMSwtMV0sWzY4LDExLDIsMSw3LDYsMCwtMSwtMV0sWzY5LDExLDMsMiw5LDgsMCwxOCwxOV0sWzcwLDExLDQsMywxMCw5LDAsLTEsLTFdLFs3MSwxMSw1LDQsNiw1LDAsLTEsLTFdXSxbWyJtNjMiLCJtMzEiLCJtNjkiLCJtMTgiLCJiMTAwMSIsIm01MCIsIm0xMiIsIm0yOCIsIm0yNCIsIm00NCIsIm0yMSIsIm05IiwibTU1IiwibTU3IiwibTMyIiwibTEiLCJiNTAwMSIsIm0xMSIsIm0zNCIsIm00OCIsIm0zNyIsIm00NSIsIm02IiwibTIyIiwibTY3IiwibTUyIiwibTYyIiwibTI5IiwiYjEwMDQiLCJtNTkiLCJtMTkiLCJtNjQiLCJtNjUiLCJtNDAiLCJiMTAwNSIsIm0zIiwibTMzIiwibTY4IiwibTE2IiwibTQ3Il0sWyJtNjYiLCJtMTQiLCJiMTAwMCIsIm0xNyIsImIxMDAyIiwibTE1IiwibTQ2IiwibTI2IiwiYjEwMDMiLCJtNjEiLCJtNTMiLCJtMjMiLCJtNTQiLCJtNTgiLCJtMzUiLCJtMTAiLCJiNTAwMiIsIm01NiIsIm00OSIsIm00MSIsIm0yMCIsIm0zOCIsIm03MSIsIm04IiwibTMwIiwibTUiLCJtMzYiLCJtMjciLCJtMjUiLCJtMzkiLCJtNyIsIm02MCIsIm0yIiwibTUxIiwibTQzIiwibTAiLCJtNCIsIm0xMyIsIm00MiIsIm03MCJdXSxbWzEwMDAsMzAsIlByb3N0byBpZ3JpxaHEjWUiXSxbMTAwMSwzMCwiUHJvc3RvIGlncmnFocSNZSJdLFsxMDAyLDMwLCJQcm9zdG8gaWdyacWhxI1lIl0sWzEwMDMsMzAsIlByb3N0byBpZ3JpxaHEjWUiXSxbMTAwNCwzMCwiUHJvc3RvIGlncmnFocSNZSJdLFsxMDA1LDMwLCJQcm9zdG8gaWdyacWhxI1lIl0sWzUwMDEsMTIwLCJOb8SNbmkgcHJlbW9yIl0sWzUwMDIsMTIwLCJOb8SNbmkgcHJlbW9yIl1dXQ",
rezultati: {
 63: [18, 22],  // 17:00 · 1 · LIZA POLJANČŠEK & MATIC ENIKO — LIA BERCE & JAN GOVEKAR
 31: [14, 18],  // 17:30 · 1 · NINA TOMAŽIN & KRIŠTOF GANTAR — PUNCA 9 & ROK MROULE
 69: [18, 19],  // 18:00 · 1 · MARUŠA DOLINAR & MATIC ENIKO — PUNCA 10 & JAN DOLENC
 18: [18, 21],  // 18:30 · 1 · NEŽA BERCE & JAN GOVEKAR — NINA TOMAŽIN & JUŠ BURJEK
 50: [13, 12],  // 19:30 · 1 · ERIKA MOHORIČ & LUYGGY — PUNCA 9 & JUŠ BURJEK
 12: [10, 10],  // 20:00 · 1 · NEŽA BERCE & MATIC ENIKO — PUNCA 10 & JAKA ENIKO
 28: [13, 15],  // 20:30 · 1 · LIZA POLJANČŠEK & JAN DOLENC — PUNCA 9 & JAKA KOPAČ
 24: [14, 12],  // 21:00 · 1 · NEŽA BERCE & JUŠ BURJEK — PUNCA 11 & MATIC ENIKO
 44: [14, 25],  // 21:30 · 1 · MARUŠA DOLINAR & LUYGGY — PUNCA 9 & JAN GOVEKAR
 21: null,  // 22:00 · 1 · LIA BERCE & JAN DOLENC — PUNCA 11 & ROK MROULE
 9: null,  // 22:30 · 1 · MARUŠA DOLINAR & JUŠ BURJEK — LIZA POLJANČŠEK & DOMEN DOLENC
 55: null,  // 23:00 · 1 · NINA TOMAŽIN & LUYGGY — PUNCA 11 & DAVID ŠENK
 57: null,  // 23:30 · 1 · LIZA POLJANČŠEK & ROK MROULE — PUNCA 12 & JAN DOLENC
 32: null,  // 00:00 · 1 · ERIKA MOHORIČ & DAVID ŠENK — LOTI GRUŠKO VANJAK & JAKA ENIKO
 1: null,  // 00:30 · 1 · NINA TOMAŽIN & ROK MROULE — LIZA POLJANČŠEK & JUŠ BURJEK
 11: null,  // 03:00 · 1 · LOTI GRUŠKO VANJAK & DAVID ŠENK — MAŠA VEGELJ & JAN DOLENC
 34: null,  // 03:30 · 1 · LIA BERCE & LUYGGY — PUNCA 12 & JUŠ BURJEK
 48: null,  // 04:00 · 1 · NEŽA BERCE & JAN DOLENC — LIZA POLJANČŠEK & JAKA KOPAČ
 37: null,  // 04:30 · 1 · NINA TOMAŽIN & DAVID ŠENK — PUNCA 11 & JUŠ BURJEK
 45: null,  // 05:00 · 1 · LIZA POLJANČŠEK & JAKA ENIKO — MAŠA VEGELJ & MATIC ENIKO
 6: null,  // 05:30 · 1 · NEŽA BERCE & ROK MROULE — PUNCA 9 & URBAN JEREB
 22: null,  // 06:00 · 1 · MAŠA VEGELJ & LUYGGY — PUNCA 12 & MATIC ENIKO
 67: null,  // 06:30 · 1 · NINA TOMAŽIN & JAKA KOPAČ — PUNCA 9 & DAVID ŠENK
 52: null,  // 07:00 · 1 · LIA BERCE & ROK MROULE — MAŠA VEGELJ & JAN GOVEKAR
 62: null,  // 07:30 · 1 · ERIKA MOHORIČ & JAKA KOPAČ — LOTI GRUŠKO VANJAK & JUŠ BURJEK
 29: null,  // 08:00 · 1 · LIA BERCE & URBAN JEREB — MAŠA VEGELJ & JAKA ENIKO
 59: null,  // 09:00 · 1 · MAŠA VEGELJ & JUŠ BURJEK — PUNCA 10 & KRIŠTOF GANTAR
 19: null,  // 09:30 · 1 · ERIKA MOHORIČ & DOMEN DOLENC — LIZA POLJANČŠEK & DAVID ŠENK
 64: null,  // 10:00 · 1 · PUNCA 9 & KRIŠTOF GANTAR — PUNCA 11 & JAN DOLENC
 65: null,  // 10:30 · 1 · PUNCA 10 & DAVID ŠENK — PUNCA 12 & URBAN JEREB
 40: null,  // 11:00 · 1 · LIZA POLJANČŠEK & LUYGGY — LOTI GRUŠKO VANJAK & JAKA KOPAČ
 3: null,  // 12:00 · 1 · MARUŠA DOLINAR & JAN GOVEKAR — MAŠA VEGELJ & DAVID ŠENK
 33: null,  // 12:30 · 1 · LIZA POLJANČŠEK & URBAN JEREB — PUNCA 10 & MATIC ENIKO
 68: null,  // 13:00 · 1 · ERIKA MOHORIČ & ROK MROULE — MAŠA VEGELJ & KRIŠTOF GANTAR
 16: null,  // 13:30 · 1 · LOTI GRUŠKO VANJAK & JAN DOLENC — PUNCA 9 & LUYGGY
 47: null,  // 14:00 · 1 · PUNCA 10 & JUŠ BURJEK — PUNCA 12 & KRIŠTOF GANTAR
 66: [11, 24],  // 17:00 · 2 · NEŽA BERCE & JAKA ENIKO — PUNCA 12 & LUYGGY
 14: [25, 21],  // 17:30 · 2 · ERIKA MOHORIČ & JUŠ BURJEK — MAŠA VEGELJ & URBAN JEREB
 17: [17, 13],  // 18:30 · 2 · PUNCA 11 & JAKA KOPAČ — PUNCA 12 & ROK MROULE
 15: [18, 16],  // 19:30 · 2 · LIZA POLJANČŠEK & KRIŠTOF GANTAR — LIA BERCE & DAVID ŠENK
 46: [13, 24],  // 20:00 · 2 · LOTI GRUŠKO VANJAK & ROK MROULE — PUNCA 11 & DOMEN DOLENC
 26: [22, 18],  // 20:30 · 2 · ERIKA MOHORIČ & KRIŠTOF GANTAR — PUNCA 12 & JAN GOVEKAR
 61: [12, 14],  // 21:30 · 2 · NINA TOMAŽIN & JAKA ENIKO — MAŠA VEGELJ & DOMEN DOLENC
 53: null,  // 22:00 · 2 · LOTI GRUŠKO VANJAK & MATIC ENIKO — PUNCA 12 & DAVID ŠENK
 23: null,  // 22:30 · 2 · PUNCA 9 & JAKA ENIKO — PUNCA 10 & JAKA KOPAČ
 54: null,  // 23:00 · 2 · NEŽA BERCE & URBAN JEREB — LOTI GRUŠKO VANJAK & JAN GOVEKAR
 58: null,  // 23:30 · 2 · LIA BERCE & MATIC ENIKO — PUNCA 9 & DOMEN DOLENC
 35: null,  // 00:00 · 2 · MAŠA VEGELJ & JAKA KOPAČ — PUNCA 11 & JAN GOVEKAR
 10: null,  // 00:30 · 2 · LIA BERCE & KRIŠTOF GANTAR — PUNCA 10 & LUYGGY
 56: null,  // 03:00 · 2 · ERIKA MOHORIČ & JAKA ENIKO — MARUŠA DOLINAR & JAKA KOPAČ
 49: null,  // 03:30 · 2 · NINA TOMAŽIN & URBAN JEREB — PUNCA 10 & DOMEN DOLENC
 41: null,  // 04:00 · 2 · MAŠA VEGELJ & ROK MROULE — PUNCA 9 & MATIC ENIKO
 20: null,  // 04:30 · 2 · MARUŠA DOLINAR & KRIŠTOF GANTAR — LOTI GRUŠKO VANJAK & URBAN JEREB
 38: null,  // 05:00 · 2 · ERIKA MOHORIČ & JAN DOLENC — PUNCA 10 & JAN GOVEKAR
 71: null,  // 05:30 · 2 · LIA BERCE & JUŠ BURJEK — LOTI GRUŠKO VANJAK & DOMEN DOLENC
 8: null,  // 06:00 · 2 · ERIKA MOHORIČ & JAN GOVEKAR — PUNCA 11 & JAKA ENIKO
 30: null,  // 06:30 · 2 · NEŽA BERCE & DOMEN DOLENC — MARUŠA DOLINAR & JAN DOLENC
 5: null,  // 07:00 · 2 · PUNCA 10 & URBAN JEREB — PUNCA 11 & LUYGGY
 36: null,  // 07:30 · 2 · NEŽA BERCE & KRIŠTOF GANTAR — PUNCA 12 & DOMEN DOLENC
 27: null,  // 08:00 · 2 · MARUŠA DOLINAR & DAVID ŠENK — PUNCA 10 & ROK MROULE
 25: null,  // 08:30 · 2 · NINA TOMAŽIN & DOMEN DOLENC — LOTI GRUŠKO VANJAK & LUYGGY
 39: null,  // 09:00 · 2 · MARUŠA DOLINAR & URBAN JEREB — LIA BERCE & JAKA ENIKO
 7: null,  // 09:30 · 2 · NINA TOMAŽIN & MATIC ENIKO — PUNCA 12 & JAKA KOPAČ
 60: null,  // 10:00 · 2 · NEŽA BERCE & LUYGGY — MARUŠA DOLINAR & ROK MROULE
 2: null,  // 10:30 · 2 · ERIKA MOHORIČ & MATIC ENIKO — LIA BERCE & DOMEN DOLENC
 51: null,  // 11:00 · 2 · MARUŠA DOLINAR & JAKA ENIKO — PUNCA 11 & KRIŠTOF GANTAR
 43: null,  // 11:30 · 2 · NINA TOMAŽIN & JAN DOLENC — ERIKA MOHORIČ & URBAN JEREB
 0: null,  // 12:00 · 2 · NEŽA BERCE & JAKA KOPAČ — LOTI GRUŠKO VANJAK & KRIŠTOF GANTAR
 4: null,  // 12:30 · 2 · PUNCA 9 & JAN DOLENC — PUNCA 12 & JAKA ENIKO
 13: null,  // 13:00 · 2 · NINA TOMAŽIN & JAN GOVEKAR — MARUŠA DOLINAR & DOMEN DOLENC
 42: null,  // 13:30 · 2 · NEŽA BERCE & DAVID ŠENK — LIA BERCE & JAKA KOPAČ
 70: null,  // 14:00 · 2 · LIZA POLJANČŠEK & JAN GOVEKAR — PUNCA 11 & URBAN JEREB
}
};
